# Generated by Django 5.0.2 on 2024-02-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scriptName', models.CharField(max_length=50)),
                ('scriptDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
